'use client';

import { useState, useMemo } from 'react';
import Link from 'next/link';
import { ColumnDef } from '@tanstack/react-table';
import { ArrowUpDown, MoreHorizontal, Download, Trash2, FileText, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { DataTable } from '@/components/ui/data-table';
import { useReports, useDeleteReport, useDownloadReport } from '@/services/report.service';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import { Card, CardContent } from '@/components/ui/card';
import { format } from 'date-fns';

const statusColors = {
  pending: 'secondary',
  generating: 'default',
  completed: 'outline',
  failed: 'destructive',
} as const;

const typeLabels = {
  attendance: 'Attendance',
  marks: 'Marks',
  enrollment: 'Enrollment',
  'faculty-workload': 'Faculty Workload',
  custom: 'Custom',
} as const;

export default function ReportsPage() {
  const [filters, setFilters] = useState<any>({});
  const [searchQuery, setSearchQuery] = useState('');
  const { data: reports, isLoading } = useReports(filters);
  const deleteMutation = useDeleteReport();
  const downloadMutation = useDownloadReport();

  const handleDelete = (id: string) => {
    if (!confirm('Are you sure you want to delete this report?')) {
      return;
    }

    deleteMutation.mutate(id);
  };

  const handleDownload = (id: string) => {
    downloadMutation.mutate(id);
  };

  const columns: ColumnDef<any>[] = useMemo(
    () => [
      {
        accessorKey: 'name',
        header: ({ column }) => {
          return (
            <Button
              variant="ghost"
              onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}
            >
              Report Name
              <ArrowUpDown className="ml-2 h-4 w-4" />
            </Button>
          );
        },
        cell: ({ row }) => {
          const report = row.original;
          return (
            <Link
              href={`/reports/${report.id}`}
              className="font-medium hover:underline"
            >
              {report.name}
            </Link>
          );
        },
      },
      {
        accessorKey: 'type',
        header: 'Type',
        cell: ({ row }) => {
          const type = row.getValue('type') as keyof typeof typeLabels;
          return <Badge variant="outline">{typeLabels[type]}</Badge>;
        },
      },
      {
        accessorKey: 'status',
        header: 'Status',
        cell: ({ row }) => {
          const status = row.getValue('status') as keyof typeof statusColors;
          return (
            <Badge variant={statusColors[status] || 'default'}>
              {status}
            </Badge>
          );
        },
      },
      {
        accessorKey: 'generatedAt',
        header: ({ column }) => {
          return (
            <Button
              variant="ghost"
              onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}
            >
              Generated At
              <ArrowUpDown className="ml-2 h-4 w-4" />
            </Button>
          );
        },
        cell: ({ row }) => {
          const date = row.getValue('generatedAt') as string;
          return date ? format(new Date(date), 'MMM dd, yyyy HH:mm') : 'N/A';
        },
      },
      {
        accessorKey: 'user',
        header: 'Generated By',
        cell: ({ row }) => {
          const user = row.original.user;
          return user ? `${user.firstName} ${user.lastName}` : 'System';
        },
      },
      {
        id: 'actions',
        cell: ({ row }) => {
          const report = row.original;
          const isCompleted = report.status === 'completed';
          
          return (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" className="h-8 w-8 p-0">
                  <span className="sr-only">Open menu</span>
                  <MoreHorizontal className="h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>Actions</DropdownMenuLabel>
                <DropdownMenuItem asChild>
                  <Link href={`/reports/${report.id}`}>
                    View Details
                  </Link>
                </DropdownMenuItem>
                {isCompleted && (
                  <DropdownMenuItem onClick={() => handleDownload(report.id)}>
                    <Download className="mr-2 h-4 w-4" />
                    Download
                  </DropdownMenuItem>
                )}
                <DropdownMenuSeparator />
                <DropdownMenuItem
                  className="text-red-600"
                  onClick={() => handleDelete(report.id)}
                >
                  <Trash2 className="mr-2 h-4 w-4" />
                  Delete
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          );
        },
      },
    ],
    [deleteMutation, downloadMutation]
  );

  const filteredReports = useMemo(() => {
    if (!searchQuery) return reports || [];
    
    const query = searchQuery.toLowerCase();
    return (reports || []).filter(
      (report) =>
        report.name.toLowerCase().includes(query) ||
        report.description?.toLowerCase().includes(query)
    );
  }, [reports, searchQuery]);

  return (
    <div className="container mx-auto py-10">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Reports</h1>
          <p className="text-muted-foreground mt-1">
            Generate and manage academic reports
          </p>
        </div>
        <Button asChild>
          <Link href="/reports/generate">
            <Plus className="mr-2 h-4 w-4" />
            Generate Report
          </Link>
        </Button>
      </div>

      <Card className="mb-6">
        <CardContent className="pt-6">
          <div className="grid gap-4 md:grid-cols-3">
            <div className="space-y-2">
              <Label>Search</Label>
              <Input
                placeholder="Search reports..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label>Type</Label>
              <select
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                value={filters.type || ''}
                onChange={(e) =>
                  setFilters((prev: any) => ({
                    ...prev,
                    type: e.target.value || undefined,
                  }))
                }
              >
                <option value="">All Types</option>
                <option value="attendance">Attendance</option>
                <option value="marks">Marks</option>
                <option value="enrollment">Enrollment</option>
                <option value="faculty-workload">Faculty Workload</option>
                <option value="custom">Custom</option>
              </select>
            </div>

            <div className="space-y-2">
              <Label>Status</Label>
              <select
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                value={filters.status || ''}
                onChange={(e) =>
                  setFilters((prev: any) => ({
                    ...prev,
                    status: e.target.value || undefined,
                  }))
                }
              >
                <option value="">All Status</option>
                <option value="pending">Pending</option>
                <option value="generating">Generating</option>
                <option value="completed">Completed</option>
                <option value="failed">Failed</option>
              </select>
            </div>
          </div>
        </CardContent>
      </Card>

      <DataTable
        columns={columns}
        data={filteredReports}
        isLoading={isLoading}
      />

      <div className="mt-4 text-sm text-muted-foreground text-center">
        <FileText className="inline h-4 w-4 mr-1" />
        Total: {filteredReports.length} reports
      </div>
    </div>
  );
}
